config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # create two routes -> index, show

  # get '/', to: 'flats#index'
  root 'flats#index'
  get 'show/:id', to: 'flats#show', as: 'flat'

  # create flats_controller V

  # create methods inside the flats_controller -> index, show X
  # create views for index and show X

  # the index page

  # grab the flats from -> https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json
  # assign the flats to an instance variable -> @flats
  # we loop through @flats

  # the show page
  # We use .find to get the flat we want
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats

  def index
  end

  def show
    @id = params[:id]
    @flat = @flats.find {|flat| flat['id'] == @id.to_i}
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<ul>
  <% @flats.each do |flat| %>
    <li>
      <%= link_to 'visit me', flat_path(flat['id']) %>
      <h3><%= flat['name'] %></h3>
      <p> Price: <%= flat['price'] %> <%= flat['priceCurrency'] %></p>
      <img height="80" src="<%= flat['imageUrl'] %>" />
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1> <%= @flat['name'] %> </h1>
<img src="<%= @flat['imageUrl'] %>"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livecode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>